In [67]:
import numpy as np
# list = [0, 1, 2, 3, 4, 5, 6, 7] 
# print(list)

[0, 1, 2, 3, 4, 5, 6, 7]


In [111]:
# 1d
l = np.arange(1,19)
print(l)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]


In [117]:
# 2d
l.reshape(6,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [115]:
# 3d
l.reshape(3,2,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [155]:
# 3d
j = np.random.rand(3,3,4)
print(j)

[[[0.98899967 0.44806967 0.99517    0.23673418]
  [0.10112563 0.29251185 0.97116789 0.21417405]
  [0.87390814 0.21763815 0.89965259 0.17937806]]

 [[0.58574511 0.79791383 0.96649121 0.43537136]
  [0.39249882 0.1816739  0.22920615 0.93511769]
  [0.42626742 0.76158151 0.80868216 0.85875691]]

 [[0.5648651  0.88166744 0.41331759 0.01512458]
  [0.71491999 0.41279655 0.74025193 0.88228288]
  [0.41984072 0.74937462 0.53539806 0.41636017]]]


In [153]:
j.ndim

3

In [141]:
j.shape

(3, 2, 2)

In [159]:
# Adding 1D two arrays
d1 = np.array([ 1, 2, 3])
d2 = np.array([ 3, 4, 5])

print(d1+d2)

[4 6 8]


In [161]:
# multiplying 2d two arrays
d3 = np.array([[2, 4, 6, 7],[1, 3, 5, 7]])
d4 = np.array([[3, 4, 2, 5],[2, 1, 3, 2]])
print(d3*d4)


[[ 6 16 12 35]
 [ 2  3 15 14]]


In [180]:
# Calculate the dot product of two matrices.
d3 = np.array([[2, 4, 6],
               [1, 3, 5],
              [4, 6, 2]])

d4 = np.array([[3, 4, 2],
               [2, 1, 3],
               [1, 3, 5]])

p = np.dot(d3, d4)

print(p)

[[20 30 46]
 [14 22 36]
 [26 28 36]]


In [190]:
d3 = np.array([[1, 2],
               [3, 4]])

d4 = np.array([[5, 6],
               [7, 8]])

p = np.dot(d3, d4)
print(p)

[[19 22]
 [43 50]]


In [182]:
# mean median standard deviation etc

data = [10,15,20,25,5,35,30,50,40,45]
min_value = min(data)
print(f"min value is: {min_value}")
max_value = max(data)
print(f"max value is: {max_value}")
rng = max_value - min_value
print(f"range is: {rng}")
sdeviation = np.std(data)
print(f"standard deviation is:{sdeviation}")
Q2 = np.percentile(data,50)
print(f"median quartile is: {Q2}")
Q1 = np.percentile(data, 25)
print(f"first quartile is: {Q1}")
Q3 = np.percentile(data, 75)
print(f"third quartile is: {Q3}")
IQR = Q3 - Q1
print(f"interqurtile range is: {IQR}")




min value is: 5
max value is: 50
range is: 45
standard deviation is:14.361406616345072
median quartile is: 27.5
first quartile is: 16.25
third quartile is: 38.75
interqurtile range is: 22.5


In [184]:
data = [10, 15, 20, 25, 5, 35, 30, 50, 40, 45]

# Minimum Value
min_value = min(data)
print(f"Minimum value: {min_value}")

# Maximum Value
max_value = max(data)
print(f"Maximum value: {max_value}")

# Range
range_value = max_value - min_value
print(f"Range: {range_value}")

# Standard Deviation
std_value = np.std(data)
print(f"Standard Deviation: {std_value}")

# Median (Q2)
median = np.median(data)
print(f"Median (Q2): {median}")

# Q1 (25th percentile)
q1 = np.percentile(data, 25)
print(f"Q1 (25th percentile): {q1}")

# Q2 (50th percentile, same as median)
q2 = np.percentile(data, 50)
print(f"Q2 (50th percentile, Median): {q2}")

# Q3 (75th percentile)
q3 = np.percentile(data, 75)
print(f"Q3 (75th percentile): {q3}")

# Interquartile Range (IQR)
IQR = q3 - q1
print(f"Interquartile Range (IQR): {IQR}")

# Box Plot
graph.boxplot(data, vert=False, patch_artist=True)
graph.title("Box Plot")
graph.xlabel("Values")
graph.ylabel("Box-Plot")

# Annotate Q1, Q2, and Q3
graph.axvline(q1, color='red', linestyle='dotted', label=f'Q1: {q1}')
graph.axvline(q2, color='green', linestyle='dashed', label=f'Q2 (Median): {q2}')
graph.axvline(q3, color='blue', linestyle='dashed', label=f'Q3: {q3}')
graph.legend()

graph.show()

import numpy as np

data = [10, 15, 20, 25, 5, 35, 30, 50, 40, 45]

print(f"Five Number Summary: {np.percentile(data, [0, 25, 50, 75, 100])}")


In [186]:
data = [1,3,4,6,9,5,7,33,5,6,6,6,]
minimum_value = min(data)
print("minimum value is",minimum_value)
max_value = max(data)
print("maximim value is", data)
range = max_value - minimum_value
print("range is:", range)


minimum value is 1
maximim value is [1, 3, 4, 6, 9, 5, 7, 33, 5, 6, 6, 6]
range is: 32


In [206]:
# find max and min from 2d array
d3 = np.array([[2, 4, 6],
               [1, 3, 5],
              [4, 6, 2]])
max_value = d3.max()
print("max value is: ",max_value)

min_value = d3.min()
print("min value is: ",min_value)



max value is:  6
min value is:  1


In [461]:
# for taking 

a = np.random.randint(1,1001,100)

In [463]:
np.max(a)
np.min(a)
np.std(a)

np.float64(295.8686429819828)

In [465]:
data = np.random.normal(loc=0, scale=1, size=1000)
int_data = np.round(data).astype(int)

print(int_data)
# print(data)

[ 1  1  0  0 -1  1 -1  1  1  0 -1  0 -1  4  1 -2  0  0 -1  1 -1 -1  1  0
 -1 -2 -1  0  0  1 -1 -1  1 -1  1  0 -2  0 -1  0 -1 -1 -1 -1  0  0 -1  0
  0  0  0  1  0  0 -1 -1 -1  2  1  2  0  0 -1 -1  2  0 -1  0  0  0 -2  0
  0  1 -1  1  0  1 -1 -1  0 -2 -2  0 -1 -1 -1 -1 -1  1  0 -1 -1 -1  1 -1
 -1  0 -2 -1  0  1  1  0 -1  1  0 -1  0 -1  0  0 -1 -1 -1 -1  0  1 -1  2
  1  1  0  1  2 -1  0  1  1  1  0  0  0  0  0 -2 -2 -1  0  0 -1 -1 -1  1
  1  1  0 -1  0  1  1 -2  0 -1  0  0 -1  1 -1 -1 -1 -1 -1  2  0  0 -1  1
  0 -1  1  0  1  0  0  0  2 -1  0 -1  1  0 -1  0  0  2  0  1  0  0  0 -1
  1  1  2  1  0  0 -1  0  1  2 -1  0  0  0  1 -1  1  0  0 -1  1  0 -2  1
 -1 -1  2  1 -1  1 -1 -1 -1  0  0  0 -1  1  0 -1 -1 -1  1  0  0  0  2 -1
  0 -2 -1  0  2  2  0  0  0  2  1  2 -1  0 -2  0  0  1 -1  0  1 -1 -1 -1
  0 -1  0  0  0  0 -1  0  1  0  0 -1 -1 -2  0  1  0  0 -1  0  0 -1 -1 -1
  0  0  0  0  1  1  0 -1  1  0 -1  0 -2 -1  0 -2  0  0 -2 -2 -1  0 -1 -1
  1  1  0  1  2  1  1  2 -1  1  2 -1  0  1  1 -2  2

In [467]:
mean_v = data.mean()
max_v = data.max()
min_v = data.min()
satanardeviation = np.std(data)

In [469]:
print(mean_v)
print(max_v)
print(min_v)
print(satanardeviation)

0.045452347025457744
3.6523907267966087
-3.1805903370132795
1.012298864915758


<h1>10.	Create a 2D array of shapes (5, 5) with random integers from a uniform distribution between 10 and 50</h1>

In [471]:
b = np.random.randint(10,50, size=(5,5))
print(b)

[[32 33 27 44 36]
 [14 35 34 20 34]
 [38 39 23 25 24]
 [26 35 23 40 32]
 [32 47 16 17 15]]


<h1>11.	Calculate the cumulative sum of a 1D array.
</h1>

In [474]:
ar = np.array([1, 3, 4, 6, 9, 5, 7, 33, 5, 6, 6, 6])
cs = np.cumsum(ar)
print(cs)

[ 1  4  8 14 23 28 35 68 73 79 85 91]


<h1>12.	Compute the correlation coefficient matrix of a 2D array</h1>


<h1>13.	Simulate rolling a six-sided die 1000 times and count the frequency of each outcome </h1>

In [508]:
rol = np.random.randint(1, 7, size=1000)

frequency = np.bincount(rol)[1:]

In [510]:
print(frequency)

[150 163 181 173 156 177]
